-- visits テーブル: ユーザーごとの駅チェックイン記録
-- ※ 既に本番に存在するテーブルの定義を後追いで記録したもの（src/lib/visits.ts が参照）。
--    新しい環境を作るときはこのファイルから適用する。
create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  station_id bigint not null,
  station_name text not null,
  line_name text,
  checked_in_at timestamptz not null default now(),
  last_visited_at timestamptz not null default now(),
  visit_count integer not null default 1,
  unique (user_id, station_id)
);

alter table public.visits enable row level security;

-- 自分の行だけ読み書きできる
create policy "visits_select_own" on public.visits
  for select using (auth.uid() = user_id);
create policy "visits_insert_own" on public.visits
  for insert with check (auth.uid() = user_id);
create policy "visits_update_own" on public.visits
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "visits_delete_own" on public.visits
  for delete using (auth.uid() = user_id);
